# Generated by Django 5.1.7 on 2025-03-09 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('TravelID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus')], max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Date_and_Time', models.DateTimeField()),
                ('Price', models.IntegerField()),
                ('Available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.traveloption')),
            ],
        ),
    ]
