# Generated by Django 5.1.7 on 2025-03-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_traveloption_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveloption',
            old_name='Available_seats',
            new_name='available_seats',
        ),
        migrations.RenameField(
            model_name='traveloption',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='traveloption',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='traveloption',
            old_name='Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='traveloption',
            old_name='Type',
            new_name='type',
        ),
    ]
